#!/usr/bin/python3
def add_tuple(tuple_a=(), tuple_b=()):
    if tuple_a == None or tuple_b == None:
        return
    else:
        if len(tuple_a) < 2:
            tuple_aa = (tuple_a[0], 0)
        else:
            tuple_aa = tuple_a
        if len(tuple_b) < 2:
            tuple_bb = (tuple_b[0], 0)
        else:
            tuple_bb = tuple_b
        first = int(tuple_aa[0]) + int(tuple_bb[0])
        second = int(tuple_aa[1]) + int(tuple_bb[1])
        return (first, second)
